name: Build and Deploy
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Build Rust proj
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Wasm Pack
        uses: jetli/wasm-pack-action@v0.3.0
        with:
          # Optional version of wasm-pack to install(eg. 'v0.9.1', 'latest')
          version: 'latest'

      - name: Install and Build
        env:
          BASE_HREF: koala
        run: sh build.sh

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
